version: "3"
services:
  backend:
    build: .
    depends_on:
      - "mysql"
    links:
      - mysql
      - redis
    ports:
      - "8080:8080"
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"